### ISSUE TITLE
Non-starter

### ISSUE THREAD

**Issue by AdamWagner** [skydiver/downloadstation-cli#3]
Hi  there! Very interesting idea here. Unfortunately, it fails pretty early for
me:

The config file is saved at ~/.config/configstore/downloadstation-cli.json, but
the token is not generated at first.

```
if (!url || !username || !password || !token) {
  return null;
}
```

And unfortunately, this block starting on line 16 of config-store.js prevents the token from being generated in
subsequent calls, even though line 22 of init.js _would_ do this (if not for the
entirely null config object returned from config-store).

An other note - the trailing slash should be stripped from the url when saving
the config - otherwise the request urls will have a double slash. I fixed this
by manually editing the config file.

Re: the token issue - no matter - I tried to push through by getting my session ID out of the browser
cookie. With this set properly in the config, I still got either: 

"ECONNREFUSED" if using my quickconnect URL 

or 

"Hostname/IP does not match certificate's altnames: IP: {REDACTED} is not in the cert's list:" if using the local IP address as the url.

These last two errors may be the fault of my personal settings, but I wasn't able to figure it out.

I _was_ able to successfully get a list of Download Station tasks by copying entry.cgi the request as curl from the network tab of my browser. There I noted that the copied request uses v2 of the Download Station API, and this cli appears to use V1. That's probably not a problem, but I found it curious.

**Comment by skydiver** [comment]
Hello @AdamWagner, thanks for your comments.

The first 2 errors are fixed on https://github.com/skydiver/downloadstation-cli/pull/4

Update: fix already pushed to npm, you can upgrade your package

**Comment by skydiver** [comment]
The `Hostname/IP does not match certificate's altnames` it's because you are trying to connect to an ip or hostname with an invalid certificate.

I think you have 2 options:
1. connect without https, just http://<your_ip>:5000 (port 5000 is for http)
2. use `NODE_TLS_REJECT_UNAUTHORIZED=0` environment variable before running the app

**Comment by AdamWagner** [comment]
Thank you! I'll give it another shot!
